### ISSUE TITLE
readFile should not trigger error

### ISSUE THREAD

**Issue by soulofmischief** [Jam3/babel-plugin-static-fs#16] opened 2019-05-30 00:56 UTC
Currently, using `fs.readFile` produces an error if the file cannot be statically linked.

`babel-plugin-static-fs` should not be invoked when `fs.readFile` is called if it does not support it.
This makes the plugin useless if you aren't only statically importing files.

**Comment by mattdesl** [comment] 2019-07-20 10:26
Thanks! Seems like a duplicate of #15 so let's discuss it there.

**Closed as completed by mattdesl** 2019-07-20 10:26 UTC
